### ISSUE TITLE
Create issues for improving test's week by week.

### ISSUE THREAD

**Issue by b0noI** [Kovalevskyi-Academy/Zeus#10]

**Comment by seralekseenko** [comment]
I need more details about issue. )

**Comment by seralekseenko** [comment]
>yes, you will need to go one by one, fail each test, see output and see if it make sense
[19:00]
>it is is clear what input was, what is expected output, and why test have failed
[19:00]
>Zeus need to learn how to communicate on a mortal language

**Comment by EcstasyAwesome** [comment]
maybe we should create some pattern of prints

**Comment by seralekseenko** [comment]
I have created issues for week0, week1, week2, week3.
