### ISSUE TITLE
Тесты не позволяют использовать код из jcb w1 d1 (класс Sorting метод sort) в AWJ d0 в интерфейсе Sort

### ISSUE THREAD

**Issue by irekminn** [Kovalevskyi-Academy/Zeus#119]
В задании jcb w1 d1, в классе Sorting, в методе sort, необходимо выкидывать исключение NullPointerException:

sortWithNullComparatorAndEmptyArray() - ←[31mBAD←[m
←[31mInput array was empty & comparator was null! Where is 'NullPointerException

если пришел пустой массив.

При попытке использования данного метода в AWJ d0 в интерфейсе Sort ситуация обратная проверка:

testSortWithoutComparatorWithSizeZeroElements() - ←[31mBAD←[m
←[31mThrown unexpected java.lang.NullPointerException: Arrays is empty
at academy.kovalevskyi.algorithms.week0.day0.Sort.sort(Sort.java:14)←[m

ругается на выброшенное исключение. Если из кода метода убрать проверку на длину 0, то все отлично работает. Т.е. получается копипаст уже реализованного метода, но без проверки на длину массива.

**Comment by seralekseenko** [comment]
Решение: привести тест в JCB к требованиям теста в AWJ.

**Comment by seralekseenko** [comment]
@irekminn , я проверил решение учителя и тесты — там нет проверки на длинну массива, там только проверка на null-массив. А это означает. что можно переиспользовать данные метод в  AWJ.
Предположу что ты перестарался и написал проверку длинны входящего массива, хотя тестами это никак не покрыто.
