### ISSUE TITLE
Weak test coverage AWJ w0d1

### ISSUE THREAD

**Issue by MyNameIsN0body** [Kovalevskyi-Academy/Zeus#123]
Зевс пропускает вот такой код
```
public static int findMiddleInOneGo(Node start) {
    if (start == null || start.next == null) {
      return -1;
    }
    Node p2 = start.next;
    Node p1 = p2.next;

    while (true) {
      if (p1.next == null) {
        return p2.value;
      }
      p2 = p2.next;
      p1 = p2.next;
    }
  }
```
Если список нод будет 5 или больше то код уже будет давать не верный результат.

![Снимок экрана от 2021-09-07 21-51-43](https://user-images.githubusercontent.com/26769092/132402127-9c582362-a858-49d1-97af-9b1ac04c292f.png)

**Comment by seralekseenko** [comment]
Нужно доработать и решение учителя и тесты.
