### ISSUE TITLE
AWJ W0D2 public static OptionalInt findIndex(int[] sortedArray, int target)

### ISSUE THREAD

**Issue by phrismin** [Kovalevskyi-Academy/Zeus#124]
Входные параметры: int[] sortedArray = new int[]{1,2,3,4,5,6,7}; int target = 10;
   Метод зациклен и тест проходит.

**Comment by seralekseenko** [comment]
Нужно больше  ~золота~ деталей. :)

**Comment by phrismin** [comment]
Метод пытается найти число, которого нет в массиве - бесконечно обрабатывает массив. Такой метод проходит проверку

**Comment by aleskarova** [comment]
@phrismin, добавь сюда, пожалайста, код метода, который проходит проверку, хотя и не должен)

**Comment by phrismin** [comment]
public static OptionalInt findIndex(int[] sortedArray, int target) {
    int start = 0;
    int end = sortedArray.length - 1;
    while (start <= end) {
      int middle = start + (end - start) / 2;
      if (target < sortedArray[middle]) {
        end = middle;
      } else if (target > sortedArray[middle]) {
        start = middle;
      } else {
        return OptionalInt.of(middle);
      }
    }
    return OptionalInt.empty();
  }
