### ISSUE TITLE
w1d0

### ISSUE THREAD

**Issue by AliaksandrMakaranka** [Kovalevskyi-Academy/Zeus#176]
![Screenshot from 2022-08-29 14-28-22](https://user-images.githubusercontent.com/96601725/187201382-955ceeff-eed3-438d-9e65-52b98c9ee601.png)
![Screenshot from 2022-08-29 14-30-31](https://user-images.githubusercontent.com/96601725/187201414-38924572-d2a2-4128-acbb-277a64244cbb.png)
main
![Screenshot from 2022-08-29 14-32-48](https://user-images.githubusercontent.com/96601725/187201769-f0673f74-6211-4061-bc84-731286bfd5d1.png)

при запуске теста, сразу два теста становятся ОК, задание "Сортировка чисел"

**Comment by seralekseenko** [comment]
Все верно. Пустой массив метод должен игнорировать.
И отсутствующие тело метода прекрасно с этим справляется ))))
