### ISSUE TITLE
W0D4 добавить проверку на пустой массив в методах findIndexOfBiggestNumber() и findBiggest()

### ISSUE THREAD

**Issue by Picallo-svg** [Kovalevskyi-Academy/Zeus#183]

**Comment by Picallo-svg** [comment]
К примеру, ожидать выброс исключения или же возврата -1 в качестве индикатора некорректного аргумента

**Comment by seralekseenko** [comment]
А сейчас пустой массив просто игнорится?

**Comment by Picallo-svg** [comment]
> А сейчас пустой массив просто игнорится?

Да. Сейчас вообще нет проверки на пустой массив.

**Comment by W25X80** [comment]
I have an idea how to resolve this issue!

**Comment by seralekseenko** [comment]
Just as a memory for myself:
- how does the code that needs changes behave now?
- how will the new code differ from the old one in the context of behaviour?
- check the solution.
- check the tests.
