### ISSUE TITLE
W1D0 добавить проверку на Integer.MAX_VALUE в методе sqrt() класса NumberUtils

### ISSUE THREAD

**Issue by Picallo-svg** [Kovalevskyi-Academy/Zeus#186]

**Comment by seralekseenko** [comment]
Заголовок отличный! Но без деталей — непонятно зачем это делать и пример бы сюда.

**Comment by W25X80** [comment]
Due to integer overflow, the standard implementation of this method incorrectly processes the input Integer.MAX_VALUE.
So i propose to add this case in test method + change sqrt method + add description to students task.

What do you think about that? Is this improvement actual ?
