### ISSUE TITLE
W1D3 добавить проверку длины закольцованного списка в методе length()

### ISSUE THREAD

**Issue by Picallo-svg** [Kovalevskyi-Academy/Zeus#187]
Zeus не проверяет корректность подсчета нод в случае, когда начало списка ссылается на конец, а конец на начало.

**Comment by seralekseenko** [comment]
Отдельно проверить допустимость закольцованого списка в рамках текущего кода.

Эсли улучшение возможно — изменить под него и само задание.

**Comment by W25X80** [comment]
I have an idea to solve this issue. Please review a pull request.
