### ISSUE TITLE
w1d0 стоит явно указать, что метод возвращает true, если число простое и false, если составное. чтобы не было путаницы с отрицательными числами

### ISSUE THREAD

**Issue by MaksimMogachev** [Kovalevskyi-Academy/Zeus#58]
![image](https://user-images.githubusercontent.com/74994208/108036153-e9f47380-7048-11eb-874f-9ebb85707158.png)

**Comment by W25X80** [comment]
Еще рекомендация уточнить в задании по 0 и 1, т.к. они оба не простые и не составные.

**Comment by seralekseenko** [comment]
Я стесняюсь, но спрошу, а какая может быть путаница, если метод возвращает `boolean`?

**Comment by W25X80** [comment]
Изначально я просто заметил  некую нелогичность:
Если вопрос звучит «Число простое? То ответ должен быть True для всех
простых начиная с числа «2» и «false» для всех остальных: отрицательных,
нуля, единицы и составных. Вместо этого для отрицательных чисел зевс хочет
 исключение.

А вот путаницу внесло объяснение Максима что задача подразумевает true -
для простого числа и false для СОСТАВНОГО.
Я отметил, что единица и ноль не являются составными числами, поэтому по
условию задачи для них ответ не может быть ни true, ни false. Тем не менее
зевс требует false для 0 и 1.

Поэтому я предложил, что нужно или конкретизировать условие задачи или
переписать тест, чтобы он поддавался логике.

Надеюсь, мне удалось обьясниться.



Пт, 19 февр. 2021 г. в 10:59, seralekseenko <notifications@github.com>:

**Comment by W25X80** [comment]
Если что, вот ссылка на переписку
https://discord.com/channels/785728667241807903/785790983379746825/811147883709595669


Пт, 19 февр. 2021 г. в 10:59, seralekseenko <notifications@github.com>:

**Comment by W25X80** [comment]
[[https://discord.com/channels/785728667241807903/785790983379746825/811147883709595669](объяснение)](url)

**Comment by W25X80** [comment]
Подводя итог сказанному, моё предложение такое (2 варианта на выбор):
**1. Модифицировать задачу:**
**true** - для всех простых чисел
**false** - для всех составных чисел
**IllegalArgumentException() - для отрицательных, ноля и единицы.

2. Оставить задачу в текущем виде, "isPrime":
**true** - для всех простых чисел.
**false** - для отрицательных, ноля, единицы и составных.

Первый вариант выглядит интересней.

**Comment by EcstasyAwesome** [comment]
@seralekseenko так как метод возвращает **_boolean_**, нет нужды выбрасывать исключение.
если чисто простое - _**true**_, все остальное - _**false**_.
