### ISSUE TITLE
w1d0.Вычисление степени | negative power

### ISSUE THREAD

**Issue by rtzZ** [Kovalevskyi-Academy/Zeus#59]
В задании неучтённо, то что степень может быть отрицательная. 
Рекомендации: изменить вывод метода на float, добавить соответствующий unit test

**Comment by seralekseenko** [comment]
Resolved bu https://github.com/Kovalevskyi-Academy/CodingBootcamp/pull/67/commits/5066e8b8251f8d0a388c60286401341211436f51
