### ISSUE TITLE
w0d4. findBiggest

### ISSUE THREAD

**Issue by rtzZ** [Kovalevskyi-Academy/Zeus#63]
Не учтена ситуация, когда на вход подаются одинаковые числа.
например 3 и 3 
`if (3>3) {
return 3
} elsen if (3<3) {return 3} `
Решения для такой задачи нет потому что 3>3 False и 3<3 False
Предложение: Изменить формулировку на: "Этот метод принимает на вход два|три целых числа и возвращает любое|первое|последнее большее из них."

**Comment by EcstasyAwesome** [comment]
>Returns the greater of two int values. That is, the result is the argument closer to the value of Integer.MAX_VALUE. If the arguments have the same value, the result is that same value.

_java.lang.Math.max()_

**Comment by rtzZ** [comment]
Ключевое слово "same"!
В заданиях его точно нет.

**Comment by EcstasyAwesome** [comment]
@rtzZ это логически понятно, но я создал соответствующую пометку для внесения правок.
