### ISSUE TITLE
jcb. в w2d3 лист стоит переименовать в ноду

### ISSUE THREAD

**Issue by MaksimMogachev** [Kovalevskyi-Academy/Zeus#65]

**Comment by seralekseenko** [comment]
Все переименовал и сделал. Вот ссылка на задание: https://docs.google.com/document/d/1_cSXg5A8Q0CU-Q_Lctd6HIQw3BBYY3bdMwZHCTkK2nc/edit#

Мне бы еще доступ на папку с текущими заданиями на гугл диске кто бы дал? ))
Доступ на мыло: htivepadlo@gmail.com
