### ISSUE TITLE
Артефакт при прохождении тестов w1d2 (Zeus 7.0)

### ISSUE THREAD

**Issue by W25X80** [Kovalevskyi-Academy/Zeus#66]
<img width="376" alt="Снимок экрана 2021-02-20 в 19 49 41" src="https://user-images.githubusercontent.com/78695319/108605183-f06d4d00-73b2-11eb-8881-b59452c51a6c.png">

Все тесты пройдены, но появляется артефакт RU

**Comment by EcstasyAwesome** [comment]
@W25X80 нужен код класса, который тестируется

**Comment by W25X80** [comment]
> @W25X80 нужен код класса, который тестируется

package com.kovalevskyi.academy.codingbootcamp.week1.day2;

public class StringUtils {

  public static boolean isAsciiUppercase(char ch) {
    return isAsciiCase(ch, 65, 90);
  }

  public static boolean isAsciiLowercase(char ch) {
    return isAsciiCase(ch, 97, 122);
  }

  public static boolean isAsciiNumeric(char ch) {
    return isAsciiCase(ch, 48, 57);
  }

  public static boolean isAsciiAlphabetic(char ch) {
    return (ch < 91) ? isAsciiCase(ch, 65, 90) : isAsciiCase(ch, 97, 122);
  }

  public static char toAsciiUppercase(char ch) {
    return toAscii(ch, 97, 122, -32);
  }

  public static char toAsciiLowercase(char ch) {
    return toAscii(ch, 65, 90, 32);
  }

  public static StringBuilder makeUppercase(char[] input) {
    return makeCase(input, 97, 122, -32);
  }

  public static StringBuilder makeLowercase(char[] input) {
    return makeCase(input, 65, 90, 32);
  }

  public static StringBuilder makeCamel(char[] input) {
    StringBuilder result = new StringBuilder(input.length);
    for (int i = 0; i < input.length; i++) {
      if (isAsciiAlphabetic(input[i])) {
        result.insert(i, (i % 2 == 0) ? toAsciiLowercase(input[i]) : toAsciiUppercase(input[i]));
        continue;
      }
      result.insert(i, input[i]);
    }
    return result;
  }

  public static boolean isStringAlphaNumerical(char[] input) {
    for (int i = 0; i < input.length; i++) {
      if (!(isAsciiNumeric(input[i]) || isAsciiAlphabetic(input[i]) || input[i] == 32)) {
        return false;
      }
    }
    return true;
  }

  /**
   * Доработать напильником. Зевс доволен, но проверки на пустую ячейку нет + нет проверки на
   * IllegalArgumentException.
   */
  public static char[] concatStrings(char[][] input) {

    // Calculate length & create result array
    int resultLength = 0;
    for (int i = 0; i < input.length; i++) {
      if (input[i].length != 0) {
        resultLength += input[i].length;
      }
    }
    char[] result = new char[resultLength];

    // Concat
    int position = 0;
    for (int i = 0; i < input.length; i++) {
      if (input[i].length != 0) {
        for (int j = 0; j < input[i].length; j++) {
          result[position] = input[i][j];
          position++;
        }
      }
    }
    return result;
  }

  /**
   * Доработать напильником. Зевс доволен, но нет проверки на '-' в средине массива. Так же Зевс не
   * проверяет входящий массив на нулевую длину.
   */
  public static int toInt(char[] input) {
    int output = 0;
    boolean hasMinus = false;
    int position = 0;
    if (input[0] == '-') {
      hasMinus = true;
      position++;
    }
    for (int i = position; i < input.length; i++) {
      if (!isAsciiCase(input[i], 48, 57)) {
        throw new NumberFormatException();
      }
      output = output * 10 + input[i] - 48;
    }
    return hasMinus ? -output : output;
  }

  /** Secondary methods. */
  private static boolean isAsciiCase(char ch, int low, int high) {
    if (ch > 255) {
      throw new IllegalArgumentException();
    }
    if (ch >= low && ch <= high) {
      return true;
    }
    return false;
  }

  private static char toAscii(char ch, int low, int high, int delta) {
    if (ch > 255) {
      throw new IllegalArgumentException();
    }
    if (ch >= low && ch <= high) {
      return (char) (delta + ch);
    }
    return ch;
  }

  private static StringBuilder makeCase(char[] ch, int low, int high, int delta) {
    StringBuilder result = new StringBuilder(ch.length);
    for (int i = 0; i < ch.length; i++) {
      if (ch[i] > 255) {
        throw new IllegalArgumentException();
      }
      if (ch[i] >= low && ch[i] <= high) {
        result.insert(i, (char) (ch[i] + delta));
        continue;
      }
      result.insert(i, ch[i]);
    }
    return result;
  }
}

**Comment by EcstasyAwesome** [comment]
Fixed
