### ISSUE TITLE
CodingBootcamp-1.0.jar  Некорректный вывод при количестве частей 14, 17 и т.д.

### ISSUE THREAD

**Issue by Picallo-svg** [Kovalevskyi-Academy/Zeus#68]
При входном параметре 14 или 17, progresbar доходит только до 99%.

**Comment by Picallo-svg** [comment]
<img width="938" alt="Снимок экрана 2021-02-25 в 10 22 09" src="https://user-images.githubusercontent.com/55140111/109153881-2bd29780-7776-11eb-9307-19a0b41f85f2.png">

**Comment by EcstasyAwesome** [comment]
done
