### ISSUE TITLE
Google Cloud Repositories - вопрос!

### ISSUE THREAD

**Issue by Alatreon101** [Kovalevskyi-Academy/Zeus#75]
Доброго вечера!
В google cloud rep помимо моего хранилища, созданного на прошлом потоке, существует еще одно с названием jcb-mar-2021-kovalevskyi-academy. В нем находятся файлы с расширением Main.java и Main.class.
Как мы выяснили в live coding, оно создано одним из участников который первый его создал. Есть мнение, что нужно работать с этим хранилищем, но в разных ветках, либо это баг.  Что со всем этим в итоге делать? 
Скрины во вложении.
Спасибо!

![Снимок экрана 2021-03-10 в 18 09 16](https://user-images.githubusercontent.com/66429520/110660750-ed58c600-81d4-11eb-9139-74e20b6fc869.png)
![Снимок экрана 2021-03-10 в 18 09 22](https://user-images.githubusercontent.com/66429520/110660754-ef228980-81d4-11eb-807c-16e4536ecc4c.png)
![Снимок экрана 2021-03-10 в 18 09 35](https://user-images.githubusercontent.com/66429520/110660763-f0ec4d00-81d4-11eb-9dcc-493321640e3d.png)

**Comment by straybro** [comment]
Да, нужно создать свою ветку и работать в ней
