### ISSUE TITLE
Week 1 Day 2 - JCB - Foreach doesn't have any tests

### ISSUE THREAD

**Issue by kasavine** [Kovalevskyi-Academy/Zeus#82]
![image](https://user-images.githubusercontent.com/4091053/118879757-f2f21c80-b8a5-11eb-8c1b-ec430f98b7cb.png)

Test says OK - my method is not implemented.

**Comment by seralekseenko** [comment]
There are several tests.

>Test says OK - my method is not implemented.

Because the interface have default foreach.

That is from interface `Iterable`:
```java
    default void forEach(Consumer<? super T> action) {
        Objects.requireNonNull(action);
        for (T t : this) {
            action.accept(t);
        }
    }
```
Может я как-то попробую через рефлексию проверить реализацию этой штуки.
