### ISSUE TITLE
Fix output message

### ISSUE THREAD

**Issue by Glebuar** [Kovalevskyi-Academy/Zeus#83]
```
mainWithWrongArgumentsNumber() - BAD         
input is: [0, 2, *, ?, 1] ==> expected: <Please provide 4 input arguments, current amount: 5
> but was: <Please provide 4 input arguments, current amount: 5>
```

**Comment by seralekseenko** [comment]
Глеб, тест проверяет наличие текста: `Please provide 4 input arguments, current amount: 5\n`.
Там по заданию нужно соблюсти шаблон сообщения.

Скажу еще таким способом: это не сообщение теста, а сообщение решения студента.

**Comment by seralekseenko** [comment]
Перевел на GoogleTruth — там чутка лучше вывод.
